//! Build-time weight generator for zilero-vad.
//!
//! Reads the upstream Silero VAD safetensors file and emits a Zig source
//! file with every model weight as a flat comptime array, re-laid out so the
//! library's inner loops run over contiguous memory.
//!
//! Usage: gen_weights <in.safetensors> <out.zig>

const std = @import("std");

const Io = std.Io;
const Writer = Io.Writer;

/// One expected tensor: its safetensors name, the emitted Zig identifier,
/// and (for conv weights) the re-layout dimensions.
const Tensor = struct {
    name: []const u8,
    id: []const u8,
    /// Text of the emitted array size, e.g. "128 * 3 * 129".
    size: []const u8,
    /// Total number of f32 elements.
    len: usize,
    /// Conv weights are stored [out][in][k] and re-laid out to [out][k][in]
    /// so the inner dot product runs over contiguous `in` values.
    in_features: ?usize,
    kernel: ?usize,
};

const tensors = [_]Tensor{
    .{ .name = "stft_conv.weight", .id = "stft_w", .size = "258 * 256", .len = 258 * 256, .in_features = null, .kernel = null },
    .{ .name = "conv1.weight", .id = "conv1_w", .size = "128 * 3 * 129", .len = 128 * 129 * 3, .in_features = 129, .kernel = 3 },
    .{ .name = "conv1.bias", .id = "conv1_b", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "conv2.weight", .id = "conv2_w", .size = "64 * 3 * 128", .len = 64 * 128 * 3, .in_features = 128, .kernel = 3 },
    .{ .name = "conv2.bias", .id = "conv2_b", .size = "64", .len = 64, .in_features = null, .kernel = null },
    .{ .name = "conv3.weight", .id = "conv3_w", .size = "64 * 3 * 64", .len = 64 * 64 * 3, .in_features = 64, .kernel = 3 },
    .{ .name = "conv3.bias", .id = "conv3_b", .size = "64", .len = 64, .in_features = null, .kernel = null },
    .{ .name = "conv4.weight", .id = "conv4_w", .size = "128 * 3 * 64", .len = 128 * 64 * 3, .in_features = 64, .kernel = 3 },
    .{ .name = "conv4.bias", .id = "conv4_b", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "lstm_cell.weight_ih", .id = "lstm_w_ih", .size = "512 * 128", .len = 512 * 128, .in_features = null, .kernel = null },
    .{ .name = "lstm_cell.bias_ih", .id = "lstm_b_ih", .size = "512", .len = 512, .in_features = null, .kernel = null },
    .{ .name = "lstm_cell.weight_hh", .id = "lstm_w_hh", .size = "512 * 128", .len = 512 * 128, .in_features = null, .kernel = null },
    .{ .name = "lstm_cell.bias_hh", .id = "lstm_b_hh", .size = "512", .len = 512, .in_features = null, .kernel = null },
    .{ .name = "final_conv.weight", .id = "final_w", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "final_conv.bias", .id = "final_b", .size = "1", .len = 1, .in_features = null, .kernel = null },
};

const values_per_line = 16;

pub fn main(init: std.process.Init) !void {
    run(init) catch |err| {
        printStderr(init.io, "gen_weights: {t}\n", .{err});
        std.process.exit(1);
    };
}

fn run(init: std.process.Init) !void {
    const io = init.io;

    var args_it = std.process.Args.Iterator.init(init.minimal.args);
    _ = args_it.next(); // argv0
    const in_path = args_it.next() orelse usageFail(io);
    const out_path = args_it.next() orelse usageFail(io);
    if (args_it.next() != null) usageFail(io);

    var arena = std.heap.ArenaAllocator.init(init.gpa);
    defer arena.deinit();

    const data = try readFile(io, arena.allocator(), in_path);
    const header_bytes: [8]u8 = data[0..8].*;
    const header_len = std.mem.readInt(u64, &header_bytes, .little);
    if (header_len == 0 or 8 + header_len > data.len) return error.InvalidHeader;
    const data_start = 8 + @as(usize, @intCast(header_len));
    const header = try std.json.parseFromSliceLeaky(std.json.Value, arena.allocator(), data[8..data_start], .{});

    const out_file = try Io.Dir.createFile(.cwd(), io, out_path, .{});
    defer Io.File.close(out_file, io);
    var wbuf: [64 * 1024]u8 = undefined;
    var writer = Io.File.writerStreaming(out_file, io, &wbuf);
    try Writer.writeAll(&writer.interface, "// Generated by tools/gen_weights.zig — do not edit.\n");

    for (tensors) |t| {
        const entry = tensorEntry(&header, t.name) orelse missingTensor(io, &header, t.name);
        const values = try extractValues(&arena, data, data_start, &t, entry);
        try emitTensor(&writer.interface, &t, values);
    }
    try Writer.flush(&writer.interface);
}

/// Prints one line to stderr and exits with `code`.
fn fail(io: Io, code: u8, comptime fmt: []const u8, args: anytype) noreturn {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, fmt, args) catch {};
    Writer.flush(&w.interface) catch {};
    std.process.exit(code);
}

fn usageFail(io: Io) noreturn {
    fail(io, 2, "usage: gen_weights <in.safetensors> <out.zig>\n", .{});
}

fn printStderr(io: Io, comptime fmt: []const u8, args: anytype) void {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, fmt, args) catch {};
    Writer.flush(&w.interface) catch {};
}

/// Reads a whole file into an allocator-owned buffer.
fn readFile(io: Io, allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const file = try Io.Dir.openFile(.cwd(), io, path, .{ .mode = .read_only });
    defer Io.File.close(file, io);
    const st = try Io.File.stat(file, io);
    var rbuf: [64 * 1024]u8 = undefined;
    var reader = Io.File.reader(file, io, &rbuf);
    return std.Io.Reader.readAlloc(&reader.interface, allocator, st.size);
}

/// Looks up a tensor entry in the parsed header object.
fn tensorEntry(header: *const std.json.Value, name: []const u8) ?*const std.json.Value {
    const obj = switch (header.*) {
        .object => |o| o,
        else => return null,
    };
    return obj.getPtr(name);
}

/// Prints the available tensor names and exits with code 1.
fn missingTensor(io: Io, header: *const std.json.Value, name: []const u8) noreturn {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, "gen_weights: tensor '{s}' not found in safetensors file.\nAvailable tensors:\n", .{name}) catch {};
    switch (header.*) {
        .object => |obj| {
            var it = obj.iterator();
            while (it.next()) |entry| {
                Writer.print(&w.interface, "  {s}\n", .{entry.key_ptr.*}) catch {};
            }
        },
        else => {},
    }
    Writer.flush(&w.interface) catch {};
    std.process.exit(1);
}

/// Reads one tensor's floats (little-endian), validating dtype and shape,
/// and re-lays out conv weights to [out][k][in].
fn extractValues(
    arena: *std.heap.ArenaAllocator,
    data: []const u8,
    data_start: usize,
    t: *const Tensor,
    entry: *const std.json.Value,
) ![]f32 {
    const obj = switch (entry.*) {
        .object => |o| o,
        else => return error.InvalidTensor,
    };
    const dtype = jsonString(&obj, "dtype") orelse return error.InvalidTensor;

    var shape: [4]usize = undefined;
    const n_dims = jsonInts(&obj, "shape", &shape) orelse return error.InvalidTensor;
    var prod: usize = 1;
    for (shape[0..n_dims]) |d| prod *= d;
    if (prod != t.len) return error.ShapeMismatch;

    var offsets: [2]usize = undefined;
    if (jsonInts(&obj, "data_offsets", &offsets) != 2) return error.InvalidTensor;
    if (offsets[1] < offsets[0] or data_start + offsets[1] > data.len) return error.InvalidTensor;
    const src = data[data_start + offsets[0] .. data_start + offsets[1]];

    const out = try arena.allocator().alloc(f32, t.len);
    if (std.mem.eql(u8, dtype, "F32")) {
        if (src.len != t.len * 4) return error.ShapeMismatch;
        for (0..t.len) |i| {
            const b: [4]u8 = src[i * 4 ..][0..4].*;
            const bits = std.mem.readInt(u32, &b, .little);
            out[i] = @as(f32, @bitCast(bits));
        }
    } else if (std.mem.eql(u8, dtype, "F16")) {
        if (src.len != t.len * 2) return error.ShapeMismatch;
        for (0..t.len) |i| {
            const b: [2]u8 = src[i * 2 ..][0..2].*;
            const bits = std.mem.readInt(u16, &b, .little);
            out[i] = @as(f32, @floatCast(@as(f16, @bitCast(bits))));
        }
    } else {
        return error.UnsupportedDtype;
    }

    if (t.in_features) |in_features| {
        const k = t.kernel orelse return error.InvalidTensor;
        const out_channels = t.len / (in_features * k);
        var dst = try arena.allocator().alloc(f32, t.len);
        for (0..out_channels) |o| {
            for (0..k) |kk| {
                for (0..in_features) |i| {
                    dst[(o * k + kk) * in_features + i] = out[(o * in_features + i) * k + kk];
                }
            }
        }
        return dst;
    }
    return out;
}

/// Reads a JSON string field.
fn jsonString(obj: *const std.json.ObjectMap, key: []const u8) ?[]const u8 {
    const v = obj.get(key) orelse return null;
    return switch (v) {
        .string => |s| s,
        else => null,
    };
}

/// Reads a JSON array of non-negative integers into `out`; returns its length.
fn jsonInts(obj: *const std.json.ObjectMap, key: []const u8, out: []usize) ?usize {
    const v = obj.get(key) orelse return null;
    const arr = switch (v) {
        .array => |a| a,
        else => return null,
    };
    if (arr.items.len > out.len) return null;
    for (arr.items, 0..) |item, i| {
        const n = switch (item) {
            .integer => |n| n,
            else => return null,
        };
        if (n < 0) return null;
        out[i] = @intCast(n);
    }
    return arr.items.len;
}

/// Emits one tensor as a flat `pub const` with 16 hex floats per line.
fn emitTensor(w: *Writer, t: *const Tensor, values: []const f32) !void {
    if (t.len == 1) {
        try Writer.print(w, "pub const {s}: f32 = {x};\n", .{ t.id, values[0] });
        return;
    }
    try Writer.print(w, "pub const {s}: [{s}]f32 = .{{\n", .{ t.id, t.size });
    for (values, 0..) |v, i| {
        if (i > 0 and i % values_per_line == 0) try Writer.writeAll(w, "\n");
        try Writer.print(w, "{x}", .{v});
        if (i + 1 < values.len) try Writer.writeAll(w, ",");
    }
    try Writer.writeAll(w, "\n};\n");
}
