//! Build-time weight generator for zilero-vad.
//!
//! Reads the upstream Silero VAD ONNX file (v6.2, 16 kHz, opset 15) and
//! emits a Zig source file with every model weight as a flat comptime
//! array, re-laid out so the library's inner loops run over contiguous
//! memory.
//!
//! The needed initializers are top-level graph initializers with inline
//! little-endian float32 `raw_data`, so a minimal protobuf walker (varints
//! plus length-delimited fields) is enough — no protobuf library or schema.
//!
//! Usage: gen_weights <in.onnx> <out.zig>

const std = @import("std");

const Io = std.Io;
const Writer = Io.Writer;

/// One expected initializer: its ONNX name, the emitted Zig identifier, and
/// (for conv weights) the re-layout dimensions.
const Tensor = struct {
    name: []const u8,
    id: []const u8,
    /// Text of the emitted array size, e.g. "128 * 3 * 129".
    size: []const u8,
    /// Total number of f32 elements.
    len: usize,
    /// Conv weights are stored [out][in][k] and re-laid out to [out][k][in]
    /// so the inner dot product runs over contiguous `in` values.
    in_features: ?usize,
    kernel: ?usize,
};

const tensors = [_]Tensor{
    .{ .name = "model.stft.forward_basis_buffer", .id = "stft_w", .size = "258 * 256", .len = 258 * 256, .in_features = null, .kernel = null },
    .{ .name = "model.encoder.0.reparam_conv.weight", .id = "conv1_w", .size = "128 * 3 * 129", .len = 128 * 129 * 3, .in_features = 129, .kernel = 3 },
    .{ .name = "model.encoder.0.reparam_conv.bias", .id = "conv1_b", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "model.encoder.1.reparam_conv.weight", .id = "conv2_w", .size = "64 * 3 * 128", .len = 64 * 128 * 3, .in_features = 128, .kernel = 3 },
    .{ .name = "model.encoder.1.reparam_conv.bias", .id = "conv2_b", .size = "64", .len = 64, .in_features = null, .kernel = null },
    .{ .name = "model.encoder.2.reparam_conv.weight", .id = "conv3_w", .size = "64 * 3 * 64", .len = 64 * 64 * 3, .in_features = 64, .kernel = 3 },
    .{ .name = "model.encoder.2.reparam_conv.bias", .id = "conv3_b", .size = "64", .len = 64, .in_features = null, .kernel = null },
    .{ .name = "model.encoder.3.reparam_conv.weight", .id = "conv4_w", .size = "128 * 3 * 64", .len = 128 * 64 * 3, .in_features = 64, .kernel = 3 },
    .{ .name = "model.encoder.3.reparam_conv.bias", .id = "conv4_b", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.rnn.weight_ih", .id = "lstm_w_ih", .size = "512 * 128", .len = 512 * 128, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.rnn.bias_ih", .id = "lstm_b_ih", .size = "512", .len = 512, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.rnn.weight_hh", .id = "lstm_w_hh", .size = "512 * 128", .len = 512 * 128, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.rnn.bias_hh", .id = "lstm_b_hh", .size = "512", .len = 512, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.decoder.2.weight", .id = "final_w", .size = "128", .len = 128, .in_features = null, .kernel = null },
    .{ .name = "model.decoder.decoder.2.bias", .id = "final_b", .size = "1", .len = 1, .in_features = null, .kernel = null },
};

const values_per_line = 16;

/// A graph initializer: its name and the raw TensorProto bytes.
const Init = struct {
    name: []const u8,
    proto: []const u8,
};

pub fn main(init: std.process.Init) !void {
    run(init) catch |err| {
        printStderr(init.io, "gen_weights: {t}\n", .{err});
        std.process.exit(1);
    };
}

fn run(init: std.process.Init) !void {
    const io = init.io;

    var args_it = std.process.Args.Iterator.init(init.minimal.args);
    _ = args_it.next(); // argv0
    const in_path = args_it.next() orelse usageFail(io);
    const out_path = args_it.next() orelse usageFail(io);
    if (args_it.next() != null) usageFail(io);

    var arena = std.heap.ArenaAllocator.init(init.gpa);
    defer arena.deinit();

    const data = try readFile(io, arena.allocator(), in_path);
    const graph = try graphBuffer(data);
    var inits: [128]Init = undefined;
    const n_inits = try collectInitializers(graph, inits[0..]);

    const out_file = try Io.Dir.createFile(.cwd(), io, out_path, .{});
    defer Io.File.close(out_file, io);
    var wbuf: [64 * 1024]u8 = undefined;
    var writer = Io.File.writerStreaming(out_file, io, &wbuf);
    try Writer.writeAll(&writer.interface, "// Generated by tools/gen_weights.zig — do not edit.\n");

    for (tensors) |t| {
        const entry = findInit(inits[0..n_inits], t.name) orelse missingTensor(io, inits[0..n_inits], t.name);
        const values = try extractValues(arena.allocator(), entry, &t);
        try emitTensor(&writer.interface, &t, values);
    }
    try Writer.flush(&writer.interface);
}

/// Prints one line to stderr and exits with `code`.
fn fail(io: Io, code: u8, comptime fmt: []const u8, args: anytype) noreturn {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, fmt, args) catch {};
    Writer.flush(&w.interface) catch {};
    std.process.exit(code);
}

fn usageFail(io: Io) noreturn {
    fail(io, 2, "usage: gen_weights <in.onnx> <out.zig>\n", .{});
}

fn printStderr(io: Io, comptime fmt: []const u8, args: anytype) void {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, fmt, args) catch {};
    Writer.flush(&w.interface) catch {};
}

/// Reads a whole file into an allocator-owned buffer.
fn readFile(io: Io, allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const file = try Io.Dir.openFile(.cwd(), io, path, .{ .mode = .read_only });
    defer Io.File.close(file, io);
    const st = try Io.File.stat(file, io);
    var rbuf: [64 * 1024]u8 = undefined;
    var reader = Io.File.reader(file, io, &rbuf);
    return std.Io.Reader.readAlloc(&reader.interface, allocator, st.size);
}

// ---------------------------------------------------------------------------
// Minimal protobuf reading (no library, no schema)
// ---------------------------------------------------------------------------

/// One field of a protobuf message.
const Field = struct {
    number: u32,
    wire_type: u32,
    /// Payload for wire type 2 (length-delimited).
    data: []const u8,
    /// Value for wire type 0 (varint).
    varint: u64,
};

/// Iterator over the fields of a protobuf message.
const FieldIter = struct {
    buf: []const u8,
    pos: usize,

    /// Returns the next field, or null at the end of the message.
    fn next(self: *FieldIter) !?Field {
        if (self.pos >= self.buf.len) return null;
        const tag = try readVarint(self.buf, &self.pos);
        const number = @as(u32, @intCast(tag >> 3));
        const wire_type = @as(u32, @intCast(tag & 7));
        var f = Field{ .number = number, .wire_type = wire_type, .data = "", .varint = 0 };
        switch (wire_type) {
            0 => f.varint = try readVarint(self.buf, &self.pos),
            1 => {
                if (self.pos + 8 > self.buf.len) return error.Truncated;
                self.pos += 8;
            },
            2 => {
                const len = try readVarint(self.buf, &self.pos);
                const l = @as(usize, @intCast(len));
                if (self.pos + l > self.buf.len) return error.Truncated;
                f.data = self.buf[self.pos .. self.pos + l];
                self.pos += l;
            },
            5 => {
                if (self.pos + 4 > self.buf.len) return error.Truncated;
                self.pos += 4;
            },
            else => return error.UnsupportedWireType,
        }
        return f;
    }
};

/// Reads a base-128 varint starting at `pos`, advancing `pos`.
fn readVarint(buf: []const u8, pos: *usize) !u64 {
    var result: u64 = 0;
    var shift: u32 = 0;
    while (true) {
        if (pos.* >= buf.len) return error.Truncated;
        const b = buf[pos.*];
        pos.* = pos.* + 1;
        result |= @as(u64, b & 0x7F) << @as(u6, @intCast(shift));
        if (b & 0x80 == 0) return result;
        shift = shift + 7;
        if (shift >= 64) return error.VarintTooLong;
    }
}

/// ModelProto: returns the payload of field 7 (graph).
fn graphBuffer(data: []const u8) ![]const u8 {
    var it = FieldIter{ .buf = data, .pos = 0 };
    while (try it.next()) |f| {
        if (f.number == 7 and f.wire_type == 2) return f.data;
    }
    return error.NoGraph;
}

/// GraphProto: collects the repeated field 5 (initializer) payloads.
fn collectInitializers(graph: []const u8, out: []Init) !usize {
    var it = FieldIter{ .buf = graph, .pos = 0 };
    var n: usize = 0;
    while (try it.next()) |f| {
        if (f.number == 5 and f.wire_type == 2) {
            if (n == out.len) return error.TooManyInitializers;
            out[n] = .{ .name = "", .proto = f.data };
            n += 1;
        }
    }
    for (out[0..n]) |*init| {
        init.name = try tensorName(init.proto);
    }
    return n;
}

/// TensorProto: returns the payload of field 8 (name).
fn tensorName(proto: []const u8) ![]const u8 {
    var it = FieldIter{ .buf = proto, .pos = 0 };
    while (try it.next()) |f| {
        if (f.number == 8 and f.wire_type == 2) return f.data;
    }
    return error.NoName;
}

fn findInit(inits: []const Init, name: []const u8) ?*const Init {
    for (inits) |*init| {
        if (std.mem.eql(u8, init.name, name)) return init;
    }
    return null;
}

/// Prints the available initializer names and exits with code 1.
fn missingTensor(io: Io, inits: []const Init, name: []const u8) noreturn {
    var buf: [4096]u8 = undefined;
    var w = Io.File.writerStreaming(.stderr(), io, &buf);
    Writer.print(&w.interface, "gen_weights: initializer '{s}' not found in ONNX file.\nAvailable initializers:\n", .{name}) catch {};
    for (inits) |init| {
        Writer.print(&w.interface, "  {s}\n", .{init.name}) catch {};
    }
    Writer.flush(&w.interface) catch {};
    std.process.exit(1);
}

// ---------------------------------------------------------------------------
// Tensor extraction and emission
// ---------------------------------------------------------------------------

/// Reads one initializer's floats (little-endian), validating dtype and
/// shape, and re-lays out conv weights to [out][k][in].
fn extractValues(allocator: std.mem.Allocator, init: *const Init, t: *const Tensor) ![]f32 {
    var dims: [4]usize = undefined;
    var n_dims: usize = 0;
    var data_type: u32 = 0;
    var raw: []const u8 = "";
    var float_data: []const u8 = "";

    var it = FieldIter{ .buf = init.proto, .pos = 0 };
    while (try it.next()) |f| {
        switch (f.number) {
            1 => { // dims (repeated int64, plain or packed varints)
                if (f.wire_type == 0) {
                    if (n_dims == dims.len) return error.TooManyDims;
                    dims[n_dims] = @as(usize, @intCast(f.varint));
                    n_dims += 1;
                } else if (f.wire_type == 2) {
                    var p: usize = 0;
                    while (p < f.data.len) {
                        if (n_dims == dims.len) return error.TooManyDims;
                        const v = try readVarint(f.data, &p);
                        dims[n_dims] = @as(usize, @intCast(v));
                        n_dims += 1;
                    }
                } else return error.InvalidTensor;
            },
            2 => { // data_type
                if (f.wire_type != 0) return error.InvalidTensor;
                data_type = @as(u32, @intCast(f.varint));
            },
            4 => { // float_data (packed, fallback if raw_data is absent)
                if (f.wire_type != 2) return error.InvalidTensor;
                float_data = f.data;
            },
            9 => { // raw_data
                if (f.wire_type != 2) return error.InvalidTensor;
                raw = f.data;
            },
            else => {},
        }
    }

    if (data_type != 1) return error.UnsupportedDtype; // TensorProto.FLOAT
    var prod: usize = 1;
    for (dims[0..n_dims]) |d| prod *= d;
    if (prod != t.len) return error.ShapeMismatch;

    const src = if (raw.len != 0) raw else float_data;
    if (src.len != t.len * 4) return error.ShapeMismatch;

    const out = try allocator.alloc(f32, t.len);
    for (0..t.len) |i| {
        const b: [4]u8 = src[i * 4 ..][0..4].*;
        const bits = std.mem.readInt(u32, &b, .little);
        out[i] = @as(f32, @bitCast(bits));
    }

    if (t.in_features) |in_features| {
        const k = t.kernel orelse return error.InvalidTensor;
        const out_channels = t.len / (in_features * k);
        var dst = try allocator.alloc(f32, t.len);
        for (0..out_channels) |o| {
            for (0..k) |kk| {
                for (0..in_features) |i| {
                    dst[(o * k + kk) * in_features + i] = out[(o * in_features + i) * k + kk];
                }
            }
        }
        return dst;
    }
    return out;
}

/// Emits one tensor as a flat `pub const` with 16 hex floats per line.
fn emitTensor(w: *Writer, t: *const Tensor, values: []const f32) !void {
    if (t.len == 1) {
        try Writer.print(w, "pub const {s}: f32 = {x};\n", .{ t.id, values[0] });
        return;
    }
    try Writer.print(w, "pub const {s}: [{s}]f32 = .{{\n", .{ t.id, t.size });
    for (values, 0..) |v, i| {
        if (i > 0 and i % values_per_line == 0) try Writer.writeAll(w, "\n");
        try Writer.print(w, "{x}", .{v});
        if (i + 1 < values.len) try Writer.writeAll(w, ",");
    }
    try Writer.writeAll(w, "\n};\n");
}
